[versions]
spock = "2.3-groovy-3.0"
junit = "5.10.1"
javalin = "5.6.3"
mockito = "5.8.0"
java-debug = "0.50.0"
mixin = "0.11.4+mixin.0.8.5"

gradle-nightly = "8.7-20240104001326+0000"
fabric-loader = "0.15.3"
fabric-installer = "1.0.0"

[libraries]
spock = { module = "org.spockframework:spock-core", version.ref = "spock" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
javalin = { module = "io.javalin:javalin", version.ref = "javalin" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
java-debug = { module = "com.microsoft.java:com.microsoft.java.debug.core", version.ref = "java-debug" }
mixin = { module = "net.fabricmc:sponge-mixin", version.ref = "mixin" }
gradle-nightly = { module = "org.gradle:dummy", version.ref = "gradle-nightly" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-installer = { module = "net.fabricmc:fabric-installer", version.ref = "fabric-installer" }